src/main/scala/net/ripe/rpki/publicationserver/StateActor.scala, src/test/resources/publishWithHashXmlResponse.xml, src/test/scala/net/ripe/rpki/publicationserver/PublicationServiceTest.scala
The replace and withdraw operations involve server-side hash
comparisons, so as to establish agreement between the client and the
server about the files that will be affected.  On the server side, the
hashes are generated with uppercase characters (see the Hashing
trait), but the client's hash is used unchanged, which means that the
client must also send hashes with uppercase characters for these
operations to be successful.  The relevant specification (RFC 8181)
does not mandate uppercase or lowercase characters in the hash, so
the hashes are now canonicalised before they are compared.  The
current behaviour causes problems for the rpki.net publication client,
which in at least some instances will send hashes that contain
lowercase characters.
=> [canonicalise-hashes] Canonicalise hashes before comparing them

src/main/scala/net/ripe/rpki/publicationserver/messaging/Messages.scala, src/main/scala/net/ripe/rpki/publicationserver/messaging/RrdpFlusher.scala, src/main/scala/net/ripe/rpki/publicationserver/store/fs/RemovingFileVisitor.scala, src/main/scala/net/ripe/rpki/publicationserver/store/fs/RrdpRepositoryWriter.scala
We have removal of previous sessions, but currently it is scheduled in an hour from the start. Remove them right away if the files are older than an hour.
=> Delete oldest sessions on the start right away, don't wait for an hour.

src/main/scala/net/ripe/rpki/publicationserver/Hashing.scala, src/main/scala/net/ripe/rpki/publicationserver/PublicationMessages.scala, src/main/scala/net/ripe/rpki/publicationserver/StateActor.scala, src/main/scala/net/ripe/rpki/publicationserver/messaging/RsyncFlusher.scala, src/main/scala/net/ripe/rpki/publicationserver/model/Delta.scala, src/main/scala/net/ripe/rpki/publicationserver/model/Dump.scala, src/main/scala/net/ripe/rpki/publicationserver/model/Snapshot.scala, src/main/scala/net/ripe/rpki/publicationserver/store/ObjectStore.scala, src/main/scala/net/ripe/rpki/publicationserver/store/fs/RsyncRepositoryWriter.scala, src/test/scala/net/ripe/rpki/publicationserver/HashingTest.scala, src/test/scala/net/ripe/rpki/publicationserver/model/DeltaTest.scala, src/test/scala/net/ripe/rpki/publicationserver/model/SnapshotTest.scala
This is to remove "temp-" files on the start, as sometimes they can stay there in the "working" directory and eat up all the inodes.
Also, ooopsie but there's some more changes that were supposed to be in a separate PR, such as changes in PublicationMessages.scala.
=> Delete temp directories

src/main/scala/net/ripe/rpki/publicationserver/store/ObjectStore.scala
Introduce a way to read base64-based DB so we don't have to do potentially problematic migration.
=> Make ObjectStore back-compatible with base64-based version

src/main/scala/net/ripe/rpki/publicationserver/PublicationMessages.scala, src/main/scala/net/ripe/rpki/publicationserver/PublicationService.scala, src/test/resources/publishBrokenBase64.xml, src/test/scala/net/ripe/rpki/publicationserver/PublicationServiceTest.scala
Also, refactor error processing to have more sane responses.
=> Do not crash with error 500 when Base64 in an object is malformed.

.gitlab-ci.yml
Since one image is used for transporting pipeline artifacts from one pipeline to another, suffix that image with `-artifacts` to clearly distinguish it from the _actual_ publication server image.
=> Use distinct image names

src/main/resources/db/migration/V1__tables.sql, src/main/scala/net/ripe/rpki/publicationserver/fs/RrdpRepositoryWriter.scala, src/main/scala/net/ripe/rpki/publicationserver/repository/DataFlusher.scala, src/test/scala/net/ripe/rpki/publicationserver/repository/DataFlusherTest.scala
This is to introduce the 'catch up' mechanism for deltas.
If there is more than one instance of a publication server, a situation when one of them 'freezes' the version of the DB and the others don't know about it will be common. This PR introduces correct handling of this type of situations. `updateFS` will update its RRDP/rsync repository with all serials between the last one it remembers and the one in the DB.
=> Serial generation time in db

.gitignore
Git ignore patterns are not simply paths from the project root. Hence a pattern
`store` will ignore _any_ file named `store` somewhere in the working
directory. Since we also have a java package `store`, it's unhelpful to ignore it.
=> Ignore some patterns in project root only

.gitlab-ci.yml, src/test/resources/application.conf, src/test/scala/net/ripe/rpki/publicationserver/PublicationServerBaseTest.scala
Using the regular `AppConfig` allows overrides through system properties, which
is convenient for CI builds.
=> Use `AppConfig` for test pgconfig

.gitignore, README.md, docker/publication-server-docker.conf, src/main/resources/reference.conf, src/main/scala/net/ripe/rpki/publicationserver/AppConfig.scala, src/main/scala/net/ripe/rpki/publicationserver/PublicationService.scala, src/main/scala/net/ripe/rpki/publicationserver/util/SSLHelper.scala
With this change, the publication server **requires** HTTPS for the publication protocol with client authentication. This mitigates the risk of publication server from being launched without HTTPS in a production setting by accident (ROS 2.15.3).
=> Require TLS configuration to start publication server

.github/workflows/ci.yml, src/main/resources/reference.conf, src/test/resources/application.conf
Adds GitHub CI (after #26 is merged into pg-store).
Runs CI as a github action. There is no "strange" external communication in the test (e.g. the rsync calls in pubserver build) so this should be as stable as the tests are locally...
=> Add GitHub ci

src/main/scala/net/ripe/rpki/publicationserver/fs/RrdpRepositoryWriter.scala, src/main/scala/net/ripe/rpki/publicationserver/fs/RsyncRepositoryWriter.scala, src/main/scala/net/ripe/rpki/publicationserver/package.scala, src/main/scala/net/ripe/rpki/publicationserver/repository/DataFlusher.scala
Apply the RRDP file attributes (from `RrdpRepositoryWriter`) to all RRDP
repository files written from the `DataFlusher`. This fixes possible issues with
default strict (or loose) masks, which is common in containers.
=> Fix RRDP repository file attributes

src/main/resources/db/migration/R__functions.sql, src/main/scala/net/ripe/rpki/publicationserver/store/postgresql/PgStore.scala
Reduce duplication by having a `latest_version` view. We may want to replace this with an actual table that we update whenever a new version becomes "active".
Replaces `NOT IN` conditions with `NOT EXISTS` (see https://wiki.postgresql.org/wiki/Don%27t_Do_This#Why_not.3F_5).
Simplified `DELETE` statements in `delete_old_versions`.
None of these changes should change the semantics.
Also, we can rewrite `delete_old_versions` to use a temporary table instead of a big common table expression:
```plpgsql
CREATE OR REPLACE FUNCTION delete_old_versions()
RETURNS SETOF versions AS
$$
BEGIN
CREATE TEMPORARY TABLE deleted_versions ON COMMIT DROP AS
SELECT * FROM versions
WHERE NOT EXISTS (SELECT * FROM reasonable_deltas d WHERE d.id = versions.id)
AND NOT EXISTS (SELECT * FROM latest_version lv …
```
=> Some more SQL cleanup

build.sbt, src/main/scala/net/ripe/rpki/publicationserver/parsing/StaxParser.scala
Update abandoned codehaus woodstox to the fasterxml implementation and drop the
synchronization around `reader.next`. While woodstox parsers themselves are
not thread-safe, concurrent parsing is safe by using different parsers in
different threads.
Removing the synchronization allows for parsing and validating concurrent
requests, lifting a huge bottleneck from the publication endpoint.
=> Fix XML parsing bottleneck

src/main/resources/db/migration/R__functions.sql, src/main/resources/db/migration/V1__tables.sql
Note: not a proper database migration so the database needs to be dropped and re-created. Otherwise we need to correctly drop the functions that have changed signatures due to overloading.
=> Always store SHA-256 hashes as lowercase and compare correctly

src/main/scala/net/ripe/rpki/publicationserver/model/package.scala, src/main/scala/net/ripe/rpki/publicationserver/repository/DataFlusher.scala, src/main/scala/net/ripe/rpki/publicationserver/repository/HashingSizedStream.scala, src/test/scala/net/ripe/rpki/publicationserver/repository/DataFlusherTest.scala
Note: if we want to be more defensive we may want to generate delta files also for versions where delta hash and size are `NULL`. These are skipped by the `getReasonableDeltas` query. This case shouldn't occur except for the last frozen version which we handle specially anyway, but ...
Note: the ``Should update rrdp and rsync when DB is modified by `another instance` in the meantime`` test in `DataFlusherTest` is flaky.
=> Always generate latest delta on RRDP initialisation

README.md
Addresses the comments on:
* RFC 8182 4.3 HTTPS between publication server and RP, and
* The usage of v3 of the publication protocol.
=> Clarify that TLS is done by reverse proxy and that implementation follows a draft of RFC8181

src/main/resources/db/migration/R__functions.sql, src/main/resources/db/migration/V1__tables.sql, src/main/scala/net/ripe/rpki/publicationserver/Boot.scala, src/main/scala/net/ripe/rpki/publicationserver/HealthChecks.scala, src/main/scala/net/ripe/rpki/publicationserver/PublicationService.scala, src/main/scala/net/ripe/rpki/publicationserver/repository/DataFlusher.scala, src/main/scala/net/ripe/rpki/publicationserver/store/postgresql/PgStore.scala, src/test/scala/net/ripe/rpki/publicationserver/HealthChecksTest.scala, src/test/scala/net/ripe/rpki/publicationserver/PublicationServerBaseTest.scala, src/test/scala/net/ripe/rpki/publicationserver/integration/PublicationIntegrationTest.scala, src/test/scala/net/ripe/rpki/publicationserver/store/postgresql/PgStoreTest.scala
Previously it was possible that an in-progress transaction would be
missing from a delta due to the non-transactional nature of sequence
number generation.
The main problem is that `object_log.id` may not be strictly
sequential, but we depend on this when querying a specific
version (since we only store the highest `object_log.id` per version).
Scenario:
- Client 1 starts publishing a million objects (getting ids 1
... 499_999, 500_001 ... 1_000_001)
- Client 2 publishes one object (getting id 500_000) and commits.
- Freeze version is called, creating a version with highest id
500_000. The delta only contains the object from client 2, since
client 1 has not committed yet.
- Client 1 commits, making objects 1 ... 499_999, 500_001
... 1_000_001 visible.
- Freeze version is called, creating …
=> Fix freeze version race condition

src/main/resources/db/migration/R__functions.sql, src/main/resources/db/migration/V1__tables.sql, src/main/scala/net/ripe/rpki/publicationserver/AppConfig.scala, src/main/scala/net/ripe/rpki/publicationserver/Binaries.scala, src/main/scala/net/ripe/rpki/publicationserver/Boot.scala, src/main/scala/net/ripe/rpki/publicationserver/Hashing.scala, src/main/scala/net/ripe/rpki/publicationserver/HealthChecks.scala, src/main/scala/net/ripe/rpki/publicationserver/PublicationService.scala, src/main/scala/net/ripe/rpki/publicationserver/RRDPService.scala, src/main/scala/net/ripe/rpki/publicationserver/fs/RemovingFileVisitor.scala, src/main/scala/net/ripe/rpki/publicationserver/fs/Rrdp.scala, src/main/scala/net/ripe/rpki/publicationserver/fs/RrdpRepositoryWriter.scala, src/main/scala/net/ripe/rpki/publicationserver/model/package.scala, src/main/scala/net/ripe/rpki/publicationserver/parsing/PublicationMessageParser.scala, src/main/scala/net/ripe/rpki/publicationserver/repository/DataFlusher.scala, src/main/scala/net/ripe/rpki/publicationserver/repository/HashingSizedStream.scala, src/main/scala/net/ripe/rpki/publicationserver/store/postgresql/PgStore.scala, src/test/scala/net/ripe/rpki/publicationserver/HashingTest.scala, src/test/scala/net/ripe/rpki/publicationserver/HealthChecksTest.scala, src/test/scala/net/ripe/rpki/publicationserver/PublicationServerBaseTest.scala, src/test/scala/net/ripe/rpki/publicationserver/PublicationServiceTest.scala, src/test/scala/net/ripe/rpki/publicationserver/fs/RemovingEmptyDirectoriesVisitorTest.scala, src/test/scala/net/ripe/rpki/publicationserver/fs/RemovingFileVisitorTest.scala, src/test/scala/net/ripe/rpki/publicationserver/fs/RrdpRepositoryWriterTest.scala, src/test/scala/net/ripe/rpki/publicationserver/integration/PublicationIntegrationTest.scala, src/test/scala/net/ripe/rpki/publicationserver/repository/DataFlusherTest.scala, src/test/scala/net/ripe/rpki/publicationserver/repository/HashingSizedStreamTest.scala, src/test/scala/net/ripe/rpki/publicationserver/store/postgresql/PgStoreTest.scala
Make delta and snapshot file names unpredictable, i.e.
`snapshot-nnnn.xml` and `delta-nnnn.xml`.
=> Use randomised names for RRDP files.

src/main/resources/db/migration/R__functions.sql, src/main/resources/db/migration/V1__tables.sql, src/main/scala/net/ripe/rpki/publicationserver/AppConfig.scala, src/main/scala/net/ripe/rpki/publicationserver/Binaries.scala, src/main/scala/net/ripe/rpki/publicationserver/repository/DataFlusher.scala, src/main/scala/net/ripe/rpki/publicationserver/store/postgresql/PgStore.scala, src/test/scala/net/ripe/rpki/publicationserver/integration/PublicationIntegrationTest.scala, src/test/scala/net/ripe/rpki/publicationserver/repository/DataFlusherTest.scala, src/test/scala/net/ripe/rpki/publicationserver/store/postgresql/PgStoreTest.scala
Verifies that RFC8181 clients send us minimal deltas when publishing or withdrawing objects.
Ensures the publication server generates minimal RFC8182 deltas when a new serial is generated. 
Based on the unique hash per URL PR (#47) so includes some changes from there, I will rebase if we decide not to merge that in.
=> Minimize deltas by combining object log entries

docker/publication-server-docker.conf, src/main/resources/reference.conf
Alternative approach: Only raise it for the publication call based on how many objects are received. I think with 20s, setting it during request processing is fine.
=> Raise request timemout and allow it to be set through environment variable

.github/workflows/ci.yml
Build and push the ripencc/rpki-publication-server:latest image from Github
Actions `pg-store` branch.
Images are pushed to Docker Hub at https://hub.docker.com/r/ripencc/rpki-publication-server.
Note that when `pg-store` finally merges into `main` we have to adjust the image job condition.
=> Build and push docker image

README.md, src/main/resources/reference.conf, src/main/scala/net/ripe/rpki/publicationserver/AppConfig.scala, src/main/scala/net/ripe/rpki/publicationserver/Boot.scala, src/main/scala/net/ripe/rpki/publicationserver/HealthChecks.scala, src/main/scala/net/ripe/rpki/publicationserver/RRDPService.scala, src/main/scala/net/ripe/rpki/publicationserver/repository/DataFlusher.scala, src/test/scala/net/ripe/rpki/publicationserver/HealthChecksTest.scala, src/test/scala/net/ripe/rpki/publicationserver/PublicationServerBaseTest.scala, src/test/scala/net/ripe/rpki/publicationserver/repository/DataFlusherStressTest.scala, src/test/scala/net/ripe/rpki/publicationserver/repository/DataFlusherTest.scala
Updating snapshot status whenever Data Flusher updates snapshot.  Reusing health check end point with additional snapshot status with a ready field that will be true whenever snapshot size is more than reasonable minimum snapshot-size (configurable).
=> Readiness endpoint

build.sbt
Updated Scala to 2.13.6.
Updated and cleaned up dependencies.
Removed the old codehaus repository (it no longer exists) and the unneeded JCenter repository (based on clearing the cache and updating the dependencies, didn't get any errors).
=> Prepare for PostgreSQL based 2.0 release

docker/publication-server-docker.conf, src/main/scala/net/ripe/rpki/publicationserver/HealthChecks.scala
This is to be able to configure readiness for k8s deployment and be able to run it without objects.
=> Configure minimal number of snapshot objects.

.github/workflows/dependency-graph.yml
This submits the sbt dependency graph to the dependency submission api, enabling the dependency graph in Github.
=> Track the sbt dependency graph in dependabot

.github/workflows/ci.yml, .github/workflows/docker.yml, .github/workflows/release.yml
Change the CI build of branch `main` to push an `unstable` image so that `latest` is preserved for release builds.
=> Push `latest` and version tags from release builds only
